server:
  port: 8080
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/E-Commerce
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update



