server:
  port: 8080
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/E-Commerce
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  tracing:
    endpoint: http://localhost:9411/api/v2/spans
    sampling:
      probability: 1.0

logging:
  pattern:
    correlation: "[${spring.application.name:},traceId: %X{traceId:-},spanId: %X{spanId:-}] "
  include-application-name: false
  file:
    name: D:/workspace/E-Commerce/Log/user-service.log


